### ISSUE TITLE
Issue with HarfBuzz

### ISSUE THREAD

**Issue by Condzi** [medranSolus/ZenithEngine#1]
I forked the repo and while trying to switch to the dev branch I got following error:

![image](https://user-images.githubusercontent.com/15295570/233778099-e3555597-babb-4355-8c2d-5a571b601230.png)

Any ideas? 
Thanks

**Comment by medranSolus** [comment]
Hi, are you using `build.ps1` script as described in README to initialize submodules? If you switch to other branch you have to do it again because there can be new submodules present (like in this example **HarfBuzz**).
